"""empty message

Revision ID: 1951e259977c
Revises: b0138b4f0a18
Create Date: 2022-10-14 09:56:41.086069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1951e259977c'
down_revision = 'b0138b4f0a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breweries', 'postal_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breweries', 'postal_code',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
