"""empty message

Revision ID: 54eae5848aac
Revises: 
Create Date: 2022-10-13 17:04:04.955692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54eae5848aac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breweries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('b_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('brewery_type', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('website', sa.String(length=80), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('b_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breweries')
    # ### end Alembic commands ###
