"""empty message

Revision ID: 5bd240d5a576
Revises: 5d38632bddc7
Create Date: 2022-10-14 15:43:37.625281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd240d5a576'
down_revision = '5d38632bddc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_breweries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('brewery', sa.String(length=80), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['brewery'], ['breweries.b_id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('breweries', 'flagged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breweries', sa.Column('flagged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('favorite_breweries')
    # ### end Alembic commands ###
