"""empty message

Revision ID: 826bbda15243
Revises: 923d8e6ec3b1
Create Date: 2022-10-17 11:42:57.507209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826bbda15243'
down_revision = '923d8e6ec3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_breweries_brewery_fkey', 'favorite_breweries', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('favorite_breweries_brewery_fkey', 'favorite_breweries', 'breweries', ['brewery'], ['b_id'])
    # ### end Alembic commands ###
