"""empty message

Revision ID: 94ca6f472fdf
Revises: 54eae5848aac
Create Date: 2022-10-14 09:04:55.304359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ca6f472fdf'
down_revision = '54eae5848aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breweries', sa.Column('postal_code', sa.Integer(), nullable=True))
    op.add_column('breweries', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breweries', 'phone')
    op.drop_column('breweries', 'postal_code')
    # ### end Alembic commands ###
