"""empty message

Revision ID: b0138b4f0a18
Revises: 94ca6f472fdf
Create Date: 2022-10-14 09:31:41.597563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0138b4f0a18'
down_revision = '94ca6f472fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breweries', sa.Column('website_url', sa.String(length=80), nullable=True))
    op.drop_column('breweries', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breweries', sa.Column('website', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('breweries', 'website_url')
    # ### end Alembic commands ###
