"""empty message

Revision ID: ce3f3f024287
Revises: 28a1cac389b6
Create Date: 2022-10-14 11:08:03.100397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3f3f024287'
down_revision = '28a1cac389b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breweries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('b_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('brewery_type', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website_url', sa.String(length=80), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('b_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breweries')
    # ### end Alembic commands ###
